### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by christofferqa** [eth-srl/R4#7]
I have been trying to run R4 on a few web pages, and consistently get a symbol lookup error on `_ZN7WebCore16ThreadGlobalData10staticDataE`.

For example, after running `./r4.sh brics.dk/r4` the log at `output/brics-dk-r4/runner/record.log` is as follows.

```
Running  http brics.dk/r4  @  /home/christofferqa/r4tmp/14226
> /home/christofferqa/R4/R4/clients/Record/bin/record -out_dir /home/christofferqa/r4tmp/14226/record -ignore-mouse-move -verbose  http://brics.dk/r4
/home/christofferqa/R4/R4/clients/Record/bin/record: symbol lookup error: /home/christofferqa/R4/R4/clients/Record/bin/record: undefined symbol: _ZN7WebCore16ThreadGlobalData10staticDataE
```

Is this an issue you have seen before, and do you have any suggestions for troubleshooting? Thanks!

**Comment by sema** [comment]
Hmm, I do recall having this issues with the TheadGlobalData before.

Please make sure that your LD_LIBRARY_PATH is set such that it uses the locally compiled webkit and not the system one. Otherwise, you may need to look at the definition of ThreadGlobalData. As far as  I recall, ThreadGlobalData is defined slightly differently depending on the environment, which has caused issues earlier with how it is used  from R4.

**Comment by christofferqa** [comment]
I can confirm that setting `LD_LIBRARY_PATH` fixes the problem, thanks!
